rules:
  instruction_phrase: "Go to the inspection area, take pictures of "

  # エリアの定義
  areas:
    name: ["docking_area", "navigation_area", "search_area"]
    docking_area:
      x_range: [10.6858938, 11.1858938]
      y_range: [-3.8864698, -3.3864698]
      z_range: [3.8705872, 4.3705872]
    navigation_area:
      x_range: [10.0, 12.0]
      y_range: [-8.0, -5.0]
      z_range: [4.0, 6.0]
    search_area:
      x_range: [10.0, 12.0]
      y_range: [-11.5, -8.0]
      z_range: [4.0, 6.0]
  
  # 安全距離の定義
  safety_distance: 0.3

  # 撮影物の定義
  search_points:

    # 固定対象物の定義  
    fixed:
      name: ["equipment", "airlock", "window"]
      equipment:
        position: [10.0, -9.0, 4.3]
        rotation: [0.0, 0.0, 0.0]
      airlock:
        position: [10.925918579101562, -10.028264999389648, 5.313942909240723]
        rotation: [0.0, 0.0, 1.57]
      window:
        position: [11.7, -11.364152908325195, 4.573802947998047]
        rotation: [0.0, 0.0, 1.57]

    # 可搬対象物の定義
    portable_objects:
      name: ["laptop", "tape", "coke", "ctb_1023", "ctb_1456", "ctb_2305", "ctb_2789", "ctb_4678", "astrobee_freeflyer"]
      laptop:
        position: [10.5, -9.0, 4.8]
        rotation: [1.0, 0.0, 0.0]
        model_folder: "Travel_Mate_P_series_Notebook/meshes/model.obj"
      tape:
        position: [11.5, -10.0, 4.8]
        rotation: [1.57, 0.0, 0.0]
        model_folder: "Shurtape_Gaffers_Tape_Silver_2_x_60_yd/meshes/model.obj"
      coke:
        position: [10.7, -10.8, 4.5]
        rotation: [1.57, 0.0, 0.0]
        model_folder: "Coke Can Steel/meshes/model.obj"
      ctb_1023:
        position: [10.0, -10.5, 4.3]
        rotation: [0.0, 0.0, 0.0]
        model_folder: "CTB_1023"
      ctb_1456:
        position: [10.0, -10.5, 4.3]
        rotation: [0.0, 0.0, 0.0]
        model_folder: "CTB_1456"
      ctb_2305:
        position: [10.0, -10.5, 4.3]
        rotation: [0.0, 0.0, 0.0]
        model_folder: "CTB_2305"
      ctb_2789:
        position: [10.0, -10.5, 4.3]
        rotation: [0.0, 0.0, 0.0]
        model_folder: "CTB_2789"
      ctb_4678:
        position: [10.0, -10.5, 4.3]
        rotation: [0.0, 0.0, 0.0]
        model_folder: "CTB_4678"
      astrobee_freeflyer:
        position: [11.0, -9.5, 4.8]
        rotation: [0.0, 0.0, 0.0]
        model_folder: "astrobee_freeflyer"

    # 宇宙飛行士の定義
    human_templates:
      name: ["person_a", "person_b", "person_c", "person_d", "person_e", "person_f", "person_g"]
      person_a:
        model_folder: "float_blue.dae"
      person_b:
        model_folder: "float_orange.dae"
      person_c:
        model_folder: "float_purple.dae"
      person_d:
        model_folder: "float2_blue.dae"
      person_e:
        model_folder: "float2_green.dae"
      person_f:
        model_folder: "float2_orange.dae"
      person_g:
        model_folder: "float2_purple.dae"

    # 宇宙飛行士の固定された場所の定義
    human_obstacles:
      publish_tf: true
      name: ["human_pos_1", "human_pos_2"]
      human_pos_1:
        position: [11.2, -6.0, 5.0]
        rotation: [0.0, 0.0, 1.57]
      human_pos_2:
        position: [11.2, -7.0, 5.0]
        rotation: [0.0, 0.0, 1.57]

  # 撮影成功の条件
  capture_conditions:
    distance_threshold: 1.0
    dot_product_threshold: 0.866

  # 安全距離ボーナスの条件
  safety_conditions:
    distance_threshold: 0.4

  # スコアシートの定義
  scoring:
    start_task:
      departure: 10
    navigation_task:
      reach_goal: 20
      avoid_obstacle: 10
      safety_bonus: 20
    search_task:
      fixed_object_capture: 20
      portable_object_capture: 20
    docking_task:
      docking: 20
    time_bonus:
      max_bonus: 10
